Feature/29 améliorer les messages derreurs dans la page dinscription
MaisonMONA/mona-mobile pull request #56
Opened 2024-06-14 06:26 UTC by SarahHCode

# Pull Request

## Summary
Transformation des messages d'erreurs (inclut aussi messages d'erreur Server error et Impossible de se connecter à internet!) en ion-toast. Les 3 messages d'erreurs peuvent être affichés en même temps et en français. Ajout de quelques commentaires pour améliorer la clarté. 

## Changes Made

## Screenshots (if applicable)

## Related Issues
Issue #29

## Checklist
Please ensure all the following steps are completed before submitting the pull request:

- [ ] Code passes all existing tests
- [ ] New features or changes are accompanied by appropriate tests
- [ ] Code follows the established coding style and conventions
- [ ] Documentation has been updated to reflect the changes (if applicable)
- [ ] All new and existing tests pass locally

## Additional Notes
Problème est que je ne sais pas comment faire pour que ion-toast reste là indéfinitivement jusqu'à que l'utilisateur corrige les erreurs, alors, j'ai juste augmenté la durée de ion-toast à 10 secondes.

2024-06-14 16:23 UTC, kim841 commented
<img width="517" alt="Screenshot 2024-06-14 at 11 59 05 AM" src="https://github.com/MaisonMONA/mona-mobile/assets/81833136/cfef80dd-d380-493c-9dc7-39c05fab48a4">

- Lorsque le clavier est ouvert, le champ input "Vérifier le mot de passe est caché" (tester dans pixel 8).
- Dans le code, chaque msg d'erreurs est suivi de "\n", mais lorsque le text est affiché dans le toast, les messages ne commencent pas sur une nouvelle ligne

2024-06-15 02:46 UTC, SarahHCode commented
J'ai corrigé ces deux bugs.

2024-06-18 15:24 UTC, kim841 requested changes

2024-06-18 17:32 UTC, SarahHCode commented on src/views/RegisterPage.vue
> +      // Informations obligatoires entrées?
J'ai rendu le commentaire plus clair.

2024-06-18 17:32 UTC, SarahHCode commented on src/views/RegisterPage.vue
> +        //if (password === passwordConfirm) {
Je n'étais pas sûre si on voudrait le garder, mais je l'enlève.

2024-06-18 18:16 UTC, kim841 requested changes

2024-06-18 18:16 UTC, kim841 commented on src/views/LoginPage.vue
> +      // related to ion-toast
Comme les noms des variables sont assez descriptifs, les commentaires de la ligne 80 à 83 peuvent être enlevés

2024-06-18 18:16 UTC, kim841 commented on src/views/LoginPage.vue
>  #login-alert-holder {
Comme l'id login-alert-holder n'est plus utilisé, il peut être supprimé (même chose pour ligne 226)

2024-06-18 18:16 UTC, kim841 commented on src/views/RegisterPage.vue
>  #register-alert-holder {
Comme l'idregister-alert-holder n'est plus utilisé, il peut être supprimé (même chose pour ligne 304)

2024-06-18 18:23 UTC, kim841 approved these changes

2024-06-18 18:24 UTC, merged