Feature/5 mettre une estimation de la précision de localisation
MaisonMONA/mona-mobile pull request #72
Opened 2024-06-26 06:31 UTC by SarahHCode

# Pull Request

## Summary
Made map user location's circle radius variable with "capacitor's geolocation accuracy"!

## Changes Made
Turned the user location icon to 'style' on location layer.

## Screenshots (if applicable)

## Related Issues
!!! Thought about making the radius really in meters on the map because "capacitor geolocation accuracy" returns accuracy in meters, but not sure it's a good idea because if the radius is always too big (or too small), it could be ugly on the map and bothering to user... so thought about indicating accuracy in terms of proportion represented by the outer circle radius of the map user location icon, but not sure how... (the more the accuracy is big, the bigger the radius of outer circle)
Also, how do I test if capacitor geolocation accuracy works (updates and returns accuracy)?

## Checklist
Please ensure all the following steps are completed before submitting the pull request:

- [ ] Code passes all existing tests
- [ ] New features or changes are accompanied by appropriate tests
- [ ] Code follows the established coding style and conventions
- [ ] Documentation has been updated to reflect the changes (if applicable)
- [ ] All new and existing tests pass locally

## Additional Notes

2024-06-26 19:18 UTC, kim841 commented
Je suis stuck dans la page de chargement, car il ne retrouve pas la fonction getAccuracy
![image](https://github.com/MaisonMONA/mona-mobile/assets/81833136/8ce3b922-26e4-4fd2-a929-0d0cc1f1c243)

2024-06-26 19:32 UTC, SarahHCode commented
Oh, j'ai oublié d'ajouter les modifications dans UserData.ts dans le commit.
J'avais juste ajouté public static getAccuracy(){ return this.data.location.accuracy}.

2024-06-27 17:00 UTC, kim841 requested changes

2024-06-27 17:00 UTC, kim841 commented on src/components/MapContainer.vue
> +    <!-- <p>{{test}}</p> -->
peut être supprimé

2024-06-27 17:02 UTC, kim841 commented
2 petits bugs
- à certain moment lorsque je zoom, le cercle bleu transparent disparait
- sur un physical device, le cercle bleu transparent n'apparait pas

2024-07-08 19:49 UTC, kim841 approved these changes

2024-07-08 19:52 UTC, kim841 commented
Tu as fait du bon travail! Le code fonctionne bien!

Pour ce qui est de l'interface, il faudra voir avec Barbara si l'apparence du cercle est acceptable à ce niveau de zoom. Pour moi ça semble bon!
![image](https://github.com/MaisonMONA/mona-mobile/assets/81833136/dd0b7398-0d5c-409b-96bf-64681e0051bb)

2024-07-10 04:35 UTC, merged